# Generated by Django 3.2.9 on 2021-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('objetivos_del_milenio', 'Objetivos del Milenio'), ('onu', 'ONU'), ('organización_internacional', 'Organización internacional'), ('uncategorized', 'Sin categoría')], default='uncategorized', max_length=30),
        ),
    ]
