services:
  db:
    image: mysql:lts
    container_name: blog1-mysql-container    # <--- Custom name
    restart: always
    env_file: .env
    ports:
      - "3307:3306"    # <--- Expose MySQL on port 3307 on the host and 3306 in the container
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro

  web:
    build: .
    # image: blog1-web   # <--- default name is good
    container_name: blog1-web-container  # <--- Personalized name
    restart: always
    command: sh -c "/wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8001:8000"   # <--- Expose Django on port 8001 on the host and 8000 in the container
    depends_on:
      - db

volumes:
  db_data:
