# Generated by Django 3.2.9 on 2021-12-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='title',
        ),
    ]
